# spring:
#   h2:
#     console:
#       enabled: true

#   datasource:
#     url: jdbc:h2:tcp://localhost/~/test
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:
#   jpa:
#     hibernate: # hibernate 사용 설정
#     # 애플리케이션 실행 시점에 테이블을 다 지우고, 내가 가진 entity 정보를 보고 다시 테이블 자동 생성
#     # if exists drop table 해주고 다시 만들어준다고 보면 된다.
#       ddl-auto: create
#       # 데이터베이스 방언 설정(h2)
#       dialect: org.hibernate.dialect.H2Dialect
#     properties: # property 사용 설정
#       hibernate: # hibernate property 설정
#         show_sql: true
#         format_sql: true
#         use_sql_comments: true
#         id:
#           new_generator_mappings: true
    